/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '18-1-28 上午9:36' with Gradle 2.3
 *
 * @author Administrator, @date 18-1-28 上午9:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
